### ISSUE TITLE
lecture 10 checklist

### ISSUE THREAD

**Issue by rebeccahuynh0** [SharbelKH/banking-system#50]
Part 2 — DevOps
Carry on with your project implementation using the techniques from this and previous lectures.

- [x] Create an issue titled "Lecture 10 checklist" to track these checklist items
- [x] Carry on with your implementation adding more features to your project: use issues and PRs to track your work; add unit tests when appropriate.
- [x] List the issues and PRs you worked on during the week in the "Lecture 10 checklist" issue.
- [x] Define a few project goals for the upcoming weeks, create them as issues, list them in the "Lecture 10 checklist" issue.
- [x] Make a new release following Semantic Versioning rules.

 

❗ Deadline: Monday, May 6
