### ISSUE TITLE
lecture 11 checklist

### ISSUE THREAD

**Issue by rebeccahuynh0** [SharbelKH/banking-system#60]
- [x] create an issue titled "Lecture 11 checklist" to track these checklist items
- [x] each student has created at least two to five unit tests with matching PRs and code review
- [x] project has at least one of the following types of tests:

-    Integration tests
-    Nonfunctional tests (e.g.: performance, capacity)
-    [Optional] Property tests

- [x] code coverage of tests is increased by at least 20%.  List the "starting" and "ending" commits in the "Lecture 11 checklist" issue with the achieved percentage increase.
- [x] main is still passing/green. (and should be always from now on!)

 

❗ Deadline: Friday, May 10
