### ISSUE TITLE
lecture 12 checklist

### ISSUE THREAD

**Issue by rebeccahuynh0** [SharbelKH/banking-system#61]
- [x] Create an issue titled "Lecture 12 checklist" to track these checklist items
- [x] Project has a software license
- [x] Carry on with your implementation adding more features to your project: use issues and PRs to track your work.
- [ ] [Optional] Present your project at the Lab session on May 8. (something simple: 5 to 10 minutes)

 

❗ Deadline: Friday, May 10
